

CREATE DATABASE VBOX2324


USE VBOX2324

CREATE TABLE [USER](SNO INT IDENTITY, CODE INT PRIMARY KEY, [NAME] VARCHAR(100), 
ACTIVE VARCHAR(1), CREATED_BY VARCHAR(1), CREATED_DATETIME DATETIME, LASTUPDATED_BY VARCHAR(1), LASTUPDATED_DATETIME VARCHAR(100))

CREATE TABLE CATEGORY(SNO INT IDENTITY, CODE INT PRIMARY KEY, [NAME] VARCHAR(100), 
ACTIVE VARCHAR(1), CREATED_BY VARCHAR(1), CREATED_DATETIME DATETIME, LASTUPDATED_BY VARCHAR(1), LASTUPDATED_DATETIME VARCHAR(100))

CREATE TABLE QUANTITY(SNO INT IDENTITY, CODE INT PRIMARY KEY, [NAME] VARCHAR(100), 
ACTIVE VARCHAR(1), CREATED_BY VARCHAR(1), CREATED_DATETIME DATETIME, LASTUPDATED_BY VARCHAR(1), LASTUPDATED_DATETIME VARCHAR(100))

CREATE TABLE PRODUCT(SNO INT IDENTITY, CODE INT PRIMARY KEY, [NAME] VARCHAR(100), TAMIL_NAME NVARCHAR(50), SEARCH_NAME VARCHAR(100),
CAT_CODE INT FOREIGN KEY REFERENCES CATEGORY(CODE), QTYPE_CODE INT FOREIGN KEY REFERENCES QUANTITY(CODE), 
ACTIVE VARCHAR(1), CREATED_BY INT FOREIGN KEY REFERENCES [USER](CODE), CREATED_DATETIME DATETIME, 
LASTUPDATED_BY INT FOREIGN KEY REFERENCES [USER](CODE), LASTUPDATED_DATETIME VARCHAR(100))


SELECT * FROM [USER]
SELECT *  FROM [QUANTITY]
SELECT * FROM [CATEGORY]
SELECT *  FROM [PRODUCT]


--DROP TABLE PRODUCT